# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-09-29 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='\u90ae\u7bb1'),
        ),
    ]
